### ISSUE TITLE
if window.ui isn't in the current directory then pinsel segfaults

### ISSUE THREAD

**Issue by eepykate** [Nooo37/nanoanno#2]
Yes, I tried putting it in /usr/lib, and /usr/local/lib, rebooting and running ldconfig.

**Comment by Nooo37** [comment]
Yea I'm a little lost writing a good install procedure. Ideally I would be able to do `make` (with the app using the current directories window.ui) for testing purposes and `sudo make install` (with the app using /usr/lib/ whatever) for installations. Didn't figure out how to get a proper setup in that regard. Currently it's just determined by the `UI_FILE` definition at the beginning of `main.c`.

**Comment by eepykate** [comment]
> Currently it's just determined by the UI_FILE definition at the beginning of main.c.

Haha I noticed when I `git pull`ed the memory commit as I was getting segfaults and had to look at the diff.

There would have to be a thing to check lib locations, right?  As hardcoding it (or using a variable) really doesn't sound like a good solution to me, though admittedly I guess it isn't hard to manually change.

**Comment by Nooo37** [comment]
There is probably some idiomatic way that everyone does and I don't know of ;-;

**Comment by Nooo37** [comment]
Might be fixed. I'm now including the resource at compile time (thanks buffet). Waiting for someone to try it out

**Comment by eepykate** [comment]
Yep, seems to work now, epic.
