### ISSUE TITLE
memory leak when drawing

### ISSUE THREAD

**Issue by eepykate** [Nooo37/nanoanno#3]
whenever I draw (ie hold left mouse and move it) the memory usage goes up quite fast, but doesn't go down.

I think this may have to do with the undo logic (btw you should add ^z support), even though it still happens if I don't let go, and the memory usage doesn't go down if I "reset" the undo history (undo, make new change).  I'm assuming that it saves the previous image instead of just the changes.

**Comment by Nooo37** [comment]
@6gk Thanks for bringing that to my attention. The major leak should have been fixed now. What I mean by that is that there might very well still be small leaks but the thing that you have experienced (memory usage going through the roof / percentage points increases within seconds while doing basic drawing) shouldn't happen anymore. Would be cool if you can confirm or contradict.

**Comment by eepykate** [comment]
Yep!  Seems to be fixed.  Thanks.
