### ISSUE TITLE
Misc Usability Changes

### ISSUE THREAD

**Issue by eepykate** [Nooo37/nanoanno#4]
I'm thinking

- ^z to undo, ^Z / ^r to redo
- ctrl-alt mousewheel to increase/decrease brush size (ala gimp)
- clicking should make a dot, instead of having to move at least 1px for it to register
- shift-clicking should draw a straight line from the last draw position (ala gimp)

some (if not all) of these are probably complicated though.

Either way, nice project, gimp starts wayyy too slowly for edits like this.

**Comment by Nooo37** [comment]
The keybinds haven't been a problem and I wanted to focus more on the gnome keyboard reference anyway (https://developer.gnome.org/hig/reference/keyboard.html). Shift-clicking for doing a line should now also be possible. Oddly enough the third point was the hardest and I couldn't get it quite working for now. Will look into it another time

**Comment by eepykate** [comment]
Shit, I meant to say ^y for redo.

And awesome!  Thanks a lot!

**Comment by Nooo37** [comment]
Clicking to make a dot is now also possible (I hope I didn't break too much other stuff as a compensation in the last weeks)

**Comment by eepykate** [comment]
Pog!

I remember that a few days ago I had to recompile due to reinstall and
(details fuzzy brain mush)
I think it had another memory leak when drawing?  So I just reset to a
dozen or two commits prior and it worked.
I'll make another issue if I experience it tomorrow, about to go to bed
shortly so I can't test again.
